// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-i-lNZdCPdJPkNEGHiN7oz362I997-04',
    appId: '1:904453695362:web:941918098023c107f1519b',
    messagingSenderId: '904453695362',
    projectId: 'testnotificationapp-aebb2',
    authDomain: 'testnotificationapp-aebb2.firebaseapp.com',
    storageBucket: 'testnotificationapp-aebb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_VH5KVPSvINN5eIstGoeH8OBWR-bC3Ww',
    appId: '1:904453695362:android:0ea5b42f56ce1b3ef1519b',
    messagingSenderId: '904453695362',
    projectId: 'testnotificationapp-aebb2',
    storageBucket: 'testnotificationapp-aebb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdx1i9aQegpVXP1zcVd3gDu1onel55mE',
    appId: '1:904453695362:ios:352d2b840f2cb466f1519b',
    messagingSenderId: '904453695362',
    projectId: 'testnotificationapp-aebb2',
    storageBucket: 'testnotificationapp-aebb2.firebasestorage.app',
    iosBundleId: 'com.example.vrsErpFigma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3GyL4rSA4EJIbrpajYz0zdV2bnpB4FLw',
    appId: '1:28644865400:ios:cc0db039cf744993cd848d',
    messagingSenderId: '28644865400',
    projectId: 'vrserptest1',
    storageBucket: 'vrserptest1.firebasestorage.app',
    iosBundleId: 'com.example.vrsErpFigma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGmHmIQMIn6JF5-VyYEwUnjo332G3dCbw',
    appId: '1:28644865400:web:6b9380b89ec67392cd848d',
    messagingSenderId: '28644865400',
    projectId: 'vrserptest1',
    authDomain: 'vrserptest1.firebaseapp.com',
    storageBucket: 'vrserptest1.firebasestorage.app',
    measurementId: 'G-F6TVFK2BCM',
  );
}